### ISSUE TITLE
KL135 Color

### ISSUE THREAD

**Issue by bobbergen** [nberardi/scrypted-tplink-smarthome#2]
The light colors on the KL135 light bulb don't quite sync up correctly in HomeKit.
For example:
If you select the blue color in HomeKit, the resulting color is light blue. If you select blue in the Kasa app and then save the light bulb state in a scene in HomeKit, when the scene is recalled, the color isn't blue but light blue.
Thanks!

**Comment by nberardi** [comment]
The issue should now be fixed

**Comment by bobbergen** [comment]
Tested and color in HomeKit with KL135 bulbs is actually worse now but I have moved on from Kasa bulbs to Philips Hue bulbs. My Kasa smart plugs work great with this plugin!

**Comment by nberardi** [comment]
Hmmm… okay I am not seeing that behavior with my bulb.
